services:
  - type: web
    name: TAXI-EXPRESS
    env: docker
    plan: free

    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://taxi-express-ywvu.onrender.com
      - key: ASSET_URL
        value: https://taxi-express-ywvu.onrender.com
      - key: FORCE_HTTPS
        value: true  
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d5p2cgggjchc73ap4img-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: taxi_express_xph8
      - key: DB_USERNAME
        value: taxi_express
      - key: DB_PASSWORD
        value: TRhALGFBxsNZtJap99XkMut3Q4avQ0D7
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: LOG_CHANNEL
        value: stack
